<?php
/**
 * Feed Class
 *
 * Libreria per generare un feed
 *
 * @package		Milk
 * @author		Nicholas Valbusa - info@squallstar.it - @squallstar
 * @copyright	Copyright (c) 2011, Squallstar
 * @license		GNU/GPL (General Public License)
 * @link		http://squallstar.it
 *
 */

if ( ! defined('BASEPATH')) exit('No direct script access allowed');

Class Feed
{
	private $CI;

	public $xml;
	public $feed_head;

	public function __construct()
	{
		$this->CI = & get_instance();
		$this->CI->load->library('parser');

		$this->feed_head = array(
			'title'			=> CMS,
			'description'	=> 'A standard RSS feed generated by ' . CMS,
			'link'			=> current_url(),
			'last_update'	=> date(DATE_RFC822),
			'lang'		=> $this->CI->lang->current_language,
			'generator'		=> CMS . ' ' . MILK_VERSION
		);
	}

	public function create_new($data)
	{
		foreach ($data as $key => $val)
		{
			if ($val)
			{
				$this->feed_head[$key] = $val;
			}
		}

		$xmlstring = read_file($this->CI->config->item('templates_folder').'RSSFeed.xml');
		$xmlstring = $this->CI->parser->parse_string($xmlstring, $this->feed_head, TRUE);
     	$this->xml = new SimpleXMLElement($xmlstring);
     	return $this;
	}

	public function add_item($item)
	{
		$child = $this->xml->channel->addChild('item');
		foreach ($item as $key => $val)
		{
			$child->addChild($key, $val);
		}
		return $this;
	}

	public function render($template='feed')
	{
		$this->CI->output->enable_profiler(FALSE);
		$this->CI->view->set('feed', $this->xml->asXML());
		$this->CI->view->render_template($template, FALSE);
		return;
	}

}